import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';

export default function Home() {
  return (
    <>
      <Head>
        <title>Martial Masters Academy</title>
        <meta name='description' content='Generated by create next app' />
      </Head>
      <section className={styles['home-page']}>
        <h2>Welcome</h2>
      </section>
    </>
  );
}
